### ISSUE TITLE
Selected Chore keywords are not displayed in Chore keywords field on post a chore Page 

### ISSUE THREAD

**Issue by Nikitamisra** [ramankapur/Fonzee-iOS#32]
1. Go to Post a chore 
2. Select a chore keywords

Result : Selected Chore keywords are not displayed in Chore keywords field on post a chore Page

**Comment by navdeeptrantor** [comment]
Already fixed and can be tested in next stable build with notifications

**Comment by Nikitamisra** [comment]
Verified
