### ISSUE TITLE
Only two buttons can perform the start stop and pause functionality 

### ISSUE THREAD

**Issue by Nikitamisra** [ramankapur/Fonzee-iOS#34]
On chore description , Play and stop button is required.

To start a chore - Play button is there
On Playing the chore - Play will convert to Pause
On clicking Pause - Pause will convert to Play

Other wise at a time two play is displayed

**Comment by navdeeptrantor** [comment]
Already fixed and can be tested in next stable build with notifications

**Comment by Nikitamisra** [comment]
Verified
