### ISSUE TITLE
Message displaying at the header like "No chores found" stays so long as well it blocked me from going to back page 

### ISSUE THREAD

**Issue by Nikitamisra** [ramankapur/Fonzee-iOS#37]
1. Go to My chores 
2. Active jobs 

Result :  "No chores found" is displayed which stays so long and I cant even go back as it is above the back button

**Comment by navdeeptrantor** [comment]
This alert message depends on time. It will disappear automatically after its defined time. Also if u tap on this notification message it will disappear.
