### ISSUE TITLE
Update payment account is not working 

### ISSUE THREAD

**Issue by Nikitamisra** [ramankapur/Fonzee-iOS#51]

**Comment by navdeeptrantor** [comment]
will you please mention whole scenario and steps to reproduce? as its working at my end. Or please retry may be network issue.

**Comment by Nikitamisra** [comment]
1. Create a Payment Account by entering all the fields 
2. Edit the Payment Account 
3. Make changes 
4. Save

**Comment by navdeeptrantor** [comment]
Tried.. and its working fine.. Please share the user creds for which u trying to check.

**Comment by Nikitamisra** [comment]
Its working I don't know at that time it was not working
